server:
    port: 8080
    context-path: #/

logging:
    level:
        demo.ralph: DEBUG

spring:
    datasource:
        name: demo
        url: jdbc:mysql://192.168.0.99:3306/demo
        username: demo
        password: Demo123!@#
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
